### ISSUE TITLE
Update or add new find function allowing to search a resource only in a given namespace

### ISSUE THREAD

**Issue by tremes** [nodeshift/openshift-rest-client#109]
This is more a feature request or enhancement than a bug. I think it would be helpful to have e.g `find(deploymentName, namespace)` function to be able to find for example deployments only for given namespace.

**Comment by lholmquist** [comment]
I like the idea and i think there might have been some work done from another user #107 , although, i've asked a question about it but got no response.  So if you want to tackle this,  be my guest :)

Also,  i think all the `find` methods have this signature `find(thingName, options)`, so you could just add a namespace param in that options object

The only thing is there is this issue #71, but i don't know how far off that is.

**Comment by tremes** [comment]
@lholmquist OK thanks. https://github.com/nodeshift/openshift-rest-client/pull/107 looks promising (didn't notice that). I'll give it a try.

**Comment by lholmquist** [comment]
@tremes just wanted to point you to #113 .  This changes the api a bit(hence the semver-major) change,  but it will take care of this issue.


The new api would be more fluent, so, to find all the buildConfigs of a namespace, you could do somehting like this:  `client.apis['build.openshift.io'].v1.namespace('myproject').buildconfigs.get()`

**Comment by tremes** [comment]
@lholmquist Thanks. Yes I've seen your PR.  OK sounds good. Hm and do I really need to do `apis['build.openshift.io']` ?
This will be 2.0.0 right? I would like to try it out in my spare time.

**Comment by lholmquist** [comment]
@tremes this will happen in 2.0

and no, you don't have to do `apis['build.openshift.io']` if you don't want to,  i've aliased it to be `apis.build`, similar for the other endpoints that are "something.openshift.io"

**Comment by tremes** [comment]
OK thanks @lholmquist. I'll will try it and hopefully will give you some feedback :-).

**Comment by lholmquist** [comment]
@tremes going to close this now, since i just released 2.0.0 and this should now be possible

**Comment by tremes** [comment]
@lholmquist OK thanks for info. I hope I'll try it and will let you know.
