### ISSUE TITLE
Change github pages to use /docs directory

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/openshift-rest-client#127]

**Comment by helio-frota** [comment]
@lholmquist If I'm not wrong it seems basically to change an option

![screenshot_4](https://user-images.githubusercontent.com/6443576/64617278-90e4d280-d3b4-11e9-9c2a-276d4ea6f82d.png)

**Comment by lholmquist** [comment]
yea,  i think that is correct.   When we did it for nodeshift,  i created this issue,  then realized there was no docs :man_shrugging:

**Comment by lholmquist** [comment]
https://nodeshift.dev/openshift-rest-client/
