### ISSUE TITLE
Possible use of Axios

### ISSUE THREAD

**Issue by lholmquist** [nodeshift/openshift-rest-client#134]
The kubernetes-client, that this library uses under the covers, uses request by default, but it does allow for someone to write their own backend to use.

An axios backend could be interesting.

**Comment by helio-frota** [comment]
@lholmquist  We have plans to use an extra module to handle the promise behavior from axios?

**Comment by helio-frota** [comment]
Example using [tape-promise](https://www.npmjs.com/package/tape-promise):

```js
const tape = require('tape');
const proxyquire = require('proxyquire');
const _test = require('tape-promise').default
const test = _test(tape);

test('Should return the response.', async (t) => {
    const foo = proxyquire('../lib/axiosfoo', {});
    const response = await foo.getRedHatDotCom();
    t.equal(response.status, 200);
    t.end();
});
```
```console
TAP version 13
# Should return the response.
ok 1 should be equal

1..1
# tests 1
# pass  1

# ok
```

**Comment by lholmquist** [comment]
I don't think we need to add another module to handle the promise behavior.   It should be a somewhat simple mock of just return a promise with some mocked data

**Comment by lholmquist** [comment]
I'm going to close this for now, since it isn't really a priority.  Feel free to reopen if necessary
