### ISSUE TITLE
Need to be able to pass in the config object here

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/openshift-rest-client#147]
https://github.com/nodeshift/openshift-rest-client/blob/master/lib/openshift-rest-client.js#L88

Maybe related to #140

**Comment by lholmquist** [comment]
I think the functionality in the TODO is actually there and i probably just forgot to remove the comment

**Comment by helio-frota** [comment]
@lholmquist thanks I'll remove the TODO and close this issue later.

**Comment by lholmquist** [comment]
closing, fixed in #148
