### ISSUE TITLE
Basic Auth doesn't work with OpenShift 4

### ISSUE THREAD

**Issue by tremes** [nodeshift/openshift-rest-client#166]
The problem is the auth url (https://github.com/nodeshift/openshift-rest-client/blob/master/lib/basic-auth-request.js#L13) is different in OS4 and I think it can't be constructed this way.

I would suggest to add a new optional param to the client settings  for setting the authUrl. I'd like to try to work on this.

**Comment by lholmquist** [comment]
@tremes Go for it!

**Comment by lholmquist** [comment]
closing,  addressed in #167
