### ISSUE TITLE
Question: Why is the openshiftClient() expecting settings.config instead of just settings?

### ISSUE THREAD

**Issue by jtudelag** [nodeshift/openshift-rest-client#172]
Just a question, out of my curiosity:

Why is the  `openshiftClient({config: ..})` expecting a `.config` property inside the `seetings` object,
if that is not the standard structure of a kubeconfig generated by the kubernetes-client library?

Wouldnt be easier to just receive the object as it is, returned from by the library `config.fromKubeconfig(path)`?

Im pretty new to NodeJS so, don't be too hard ;)

config.fromKubeconfig(path);

[1] https://github.com/nodeshift/openshift-rest-client/blob/master/lib/openshift-rest-client.js#L62
[2] https://github.com/nodeshift/openshift-rest-client/blob/master/lib/openshift-rest-client.js#L72

**Comment by lholmquist** [comment]
I think the reason was because if there were settings to pass in that didn't have anything to do with the actual kube config object, then we could keep those separate.  At the moment, though it doesn't look like there are, but it makes it a little future proof

**Comment by lholmquist** [comment]
closing,  if you have any other questions, feel free to ask
