### ISSUE TITLE
[RFE] TypeScript types

### ISSUE THREAD

**Issue by jtudelag** [nodeshift/openshift-rest-client#173]
First of all, thanks for this cool library, is pretty dope!!

I'm currently working on a project where we are using Typescript instead of just plain JS.
It would be great to have the Typescript types `@types/openshift-rest-client` availables.

Thanks ;)

**Comment by lholmquist** [comment]
Thanks for using this module!

We don't have any plans at the moment for adding types in this repo,  but if someone from the community wants to contribute them to the @types project,  that would be great,  https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request

**Comment by helio-frota** [comment]
bit of progress on this:

![2020-02-17_10-59](https://user-images.githubusercontent.com/6443576/74662797-65db8780-5179-11ea-9542-e8fb4e61e8d6.png)

![2020-02-17_11-33](https://user-images.githubusercontent.com/6443576/74662807-6aa03b80-5179-11ea-829c-532a3e3606b3.png)

**Comment by lholmquist** [comment]
closing for now since we don't have plans for this.  We can re-open if someone from the community wants to send a PR
