### ISSUE TITLE
How to pass query parameters?

### ISSUE THREAD

**Issue by Dominykas97** [nodeshift/openshift-rest-client#192]
OpenShift Rest api supports query parameters but I haven't seen any examples how to pass them.
https://docs.openshift.com/container-platform/3.11/rest_api/api/v1.Pod.html#query-parameters-5

This is how I assume it would work but it doesn't.
`client.api.v1.ns(namespace).pods().get(labelSelector="someLabel");`
Is this functionality supported?

**Comment by lholmquist** [comment]
In the Nodeshift module, we use query params in a few spots.  here is one example:  https://github.com/nodeshift/nodeshift/blob/master/lib/build-config.js#L64

This is getting the list of build configs,  but it should be similar for the pod example you have above

**Comment by lholmquist** [comment]
@Dominykas97 did this answer your question?  can this be closed now?  Perhaps you might want to contribute a small example on the readme :)

**Comment by Dominykas97** [comment]
@lholmquist Yes, it is working. Thank you. You really helped me. Although, I still don't understand where does the "qs" part come from :)
Here is updated README: https://github.com/nodeshift/openshift-rest-client/pull/196/commits/9b9b7501c34e7e09ab67afec2ca51e3d6e81c49c

**Comment by lholmquist** [comment]
the client uses [request](https://www.npmjs.com/package/request#requestoptions-callback) under the hood, so those are just the request options you are passing in

**Comment by lholmquist** [comment]
closed via #196
