### ISSUE TITLE
Use safe URL joins for API calls and better status code checks

### ISSUE THREAD

**Issue by evanshortiss** [nodeshift/openshift-rest-client#262]
In `openshift-rest-client.js` the `getUserFromAuthToken` can fail if the given `settings.url` has a trailing slash. 

For example if `settings.url` is `https://$CLUSTER_HOST:6443/`, then the resulting URL becomes `https://$CLUSTER_HOST:6443//apis/user.openshift.io/v1/users/~`. Notice the double slash? This causes a 404.

I'm happy to submit a PR shortly that safely joins the URL 😄

**Comment by lholmquist** [comment]
that would be great :+1:

**Comment by lholmquist** [comment]
closed via #265
