### ISSUE TITLE
No API for config.openshift.io

### ISSUE THREAD

**Issue by DaoDaoNoCode** [nodeshift/openshift-rest-client#267]
Is there a plan to add this one to API list?

**Comment by lholmquist** [comment]
By default, the available API will get loaded from the included open-api spec file:  https://github.com/nodeshift/openshift-rest-client/blob/main/lib/specs/openshift-openapi-spec.json.gz

There might be API's on your cluster that are not in that list, so you should use the `loadFromCluster` flag, https://github.com/nodeshift/openshift-rest-client#load-api-from-a-remote-cluster to load all the availble API's from the cluster. 

In the future I would like to make this the default, and not load from that static file. Hope this helps

**Comment by lholmquist** [comment]
closing now.  feel free to re-open if needed
