### ISSUE TITLE
Fix lint issues in the code and remove the eslint comments

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/openshift-rest-client#308]
some can be found here:

```
❯ rg "// eslint"
test/openshift-client-test.js
249:  // eslint-disable-next-line n/no-path-concat
276:  // eslint-disable-next-line n/no-path-concat

test/basic-auth-request-test.js
134:      // eslint-disable-next-line n/no-callback-literal
257:      // eslint-disable-next-line n/no-callback-literal

test/authorization-server-request-test.js
130:      // eslint-disable-next-line n/no-callback-literal

test/binary-build-test.js
28:  // eslint-disable-next-line n/no-path-concat
```

**Comment by Pathholder1806** [comment]
Hey @helio-frota !
So we have to get it removed from all the JS files right ?

**Comment by helio-frota** [comment]
hi @Pathholder1806 

Yeah that means to remove the comment by fixing the code, in case eslint warns or shows errors.

**Comment by helio-frota** [comment]
I saw that you sent some PRs but for example I removed one line
and when running the tests, eslint shows the error

```
❯ npm t

> openshift-rest-client@7.0.0 pretest /home/lm/code/openshift-rest-client
> eslint --ignore-path .gitignore .


/home/lm/code/openshift-rest-client/test/basic-auth-request-test.js
  134:14  error  Unexpected literal in error position of callback  n/no-callback-literal

✖ 1 problem (1 error, 0 warnings)

npm ERR! Test failed.  See above for more details.
```

I think this issue can also be done in a single PR

**Comment by helio-frota** [comment]
Looking at this specific case ^

That can be solved like this:

```js
const message = { message: 'Error' };
return cb(message, {});
```

**Comment by helio-frota** [comment]
Thanks for the initiative :+1: 
I have updated the title to be more clear.

**Comment by helio-frota** [comment]
I noticed that the repository is missing the contributing guide so you can take a look here https://github.com/nodeshift/openshift-rest-client/pull/318 for details.

for example when you run `npm install` and then `npm test` you can see the lint running.

**Comment by Pathholder1806** [comment]
Hey @helio-frota 
I have closed all the previous PRs and I'll be taking a closer look to the problem.

**Comment by Pathholder1806** [comment]
Hey @helio-frota 
I have just checked that in my local....all the test cases are passing 

![image](https://user-images.githubusercontent.com/61896647/186590052-99683ffa-2285-46c6-8eeb-83e4d7f0955b.png)

**Comment by Pathholder1806** [comment]
Hey @helio-frota 
I have generated the new PR. Kindly review it!🙂

**Comment by helio-frota** [comment]
thank you for the contribution!
landed here https://github.com/nodeshift/openshift-rest-client/commit/7467bf4abea27e5fe51f410db72ba5d8ccf8e4bb
