### ISSUE TITLE
Issue in urls with client request

### ISSUE THREAD

**Issue by codeswriter** [nodeshift/openshift-rest-client#323]
The communication with the openshift cluster fail due a bad url string, it shows the follow error:

`Error: path must be an absolute URL or start with a slash
    at buildError (/app/node_modules/openshift-rest-client/lib/authorization-server-request.js:6:15)
    at /app/node_modules/openshift-rest-client/lib/authorization-server-request.js:39:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 'UND_ERR_INVALID_ARG'
}`

The server base url is missing in the request options path. 

Note: this issue is in the v7.1.0

**Comment by codeswriter** [comment]
I send a PR to try resolve this issue https://github.com/nodeshift/openshift-rest-client/pull/324

**Comment by lholmquist** [comment]
Thanks for the fix,  i'll release the updated version soon

**Comment by lholmquist** [comment]
7.1.1 has been released
