### ISSUE TITLE
Basic auth fails with " Uncaught TypeError: Cannot read property 'indexOf' of null" when using wrong or empty credentials

### ISSUE THREAD

**Issue by tremes** [nodeshift/openshift-rest-client#98]
This issue was introduced by my commit. The problem is at https://github.com/nodeshift/openshift-rest-client/blob/master/lib/common-request.js#L109. In this case the hash is null and thus the error. 

I would like to provide some fix.

**Comment by lholmquist** [comment]
fixed with 8d6ad07cdf77e23657d5d2a2fdcf0dd8a768ec51
